/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.gradle.project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        User user1 = new User(1, "Alex");
        User user2 = new User(1, "John");
        System.out.println(user1.isEqual(user2));
    }
}
