/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.gradle.project;

public class App {
    public static void main(String[] args) {
        System.out.println(getFigureSquare(new Quadrate(11)));
    }

    public static String getFigureSquare(Geometric figure) {
        String name = figure.getName();
        int square = figure.getSquare();
        return String.format("Square of %s is %s", name, square);
    }
}
