/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.gradle.project;

public class App {
    public static void main(String[] args) {
        var seq = new Random(100);
        var result1 = seq.getNext();
        var result2 = seq.getNext();
        System.out.println(result1 != result2);
    }
}
